class TommyGunCultistNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Darkmoon Cultist [tommy gun]";

		Decal "BloodBulletChip";
		Health 125; // 40,60,80,100,125
		Radius 20;
		Height 56 ;
		Mass 200;
		Speed 4;
		Fastspeed 5;
		MaxDropoffHeight 128;
		MinMissileChance 160;
		Scale 0.55;
		painchance 170;
		DamageFactor "Breakfast", 1.25;
		DamageFactor "Cricket", 1.5;
		DamageFactor "Bonk", 1.5;
		Painchance "Fist", 255; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Cricket", 255;
		Painchance "Bonk", 255;
		Painchance "Breakfast", 213;
		obituary "%o was made hole-y by a Fanatic";
		MONSTER;
		+NOSPLASHALERT;
		+FLOORCLIP;
		+DONTHARMSPECIES;
		+MISSILEMORE;
		+NOSPLASHALERT;
		+SLIDESONWALLS; //+DROPOFF; -NODROPOFF;
		+STRIFEDAMAGE;
		+NOINFIGHTING;
		attacksound "fanatic/attack";
		painsound "Fanatic/pain";
		deathsound "fanatic/death";
		activesound "dovile";
		seesound "zombieman/sight";
		DropItem "Clip", 192;
		DropItem "Clip", 12;
	}

	states
	{
		Spawn:  
			XFAN G 0 NoDelay;
			XFAN G 5 A_Look();
			goto Spawn+1;
			XFAN AAABBBCCCDDDFFFGGG 1 A_EEWander(0,1,3,1,1);
			XFAN B 5 A_Look();
			goto Spawn+1;
		See:
			XFAN A 0;
			XFAN A 0 { bDROPOFF = random(0,1); }
			XFAN AABBCCDDFF 1
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			XFAN A 0 A_Jump(8,"Shout");
			loop;
		Shout:
			XFAN A 0 A_AlertMonsters(256);
			XFAN A 0 A_StartSound("fanatic/sight");
			Goto See;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			XFAN G 2 bright
			{
				A_StartSound("fanatic/attack", CHAN_BODY);
				A_FaceTarget();
				A_CustomBulletAttack(10, 5.6, 1, (Random(4,6) * Random(1,2)), "BulletPuff2", 0, CBAF_NORANDOM);
				//A_SpawnProjectile("TCOTDBulletTracer", 32, 12, frandom(-5.0,5.0), CMF_OFFSETPITCH|CMF_BADPITCH, frandom(-2.8,2.8));
			}
			XFAN H 2 A_FaceTarget();
			XFAN H 0 A_MonsterRefire(48,"See");
			goto Missile;

		Frightened:
			XFAN A 0 { bFRIGHTENED = true; }
			XFAN AABBCCDDEEFF 3 A_EEChase("Melee","Missile",0,1,3,1,1);
			loop;
		Pain:
			XFAN I 3;
			XFAN I 3 A_EEPain;
			goto See;
		Pain.Bonk:
		Pain.Cricket:
			XFAN I 3;
			XFAN I 3 A_EEPain();
			XFAN II 3;
			goto See;
		Death:
			XFAN J 5 ThrustThingZ(0,10,0,0);
			XFAN K 5 A_Scream();
			XFAN L 5 A_Fall();
			XFAN MNO 5;
			XFAN P 140;
			TNT1 A 0;
			XFAN Q 0 A_Jump(192,"Twitch");
			XFAN Q -1;
			stop;
		Twitch:
			XFAN PQPQ 5;
			XFAN P 70 A_Jump(80,"Twitch");
			XFAN Q 70 A_Jump(80,"Twitch");
			XFAN P 70 A_Jump(80,"Twitch");
			XFAN Q -1;
			Stop;
		Raise:
			XFAN Q 0 A_UnHideThing();
			XFAN P 6;
			XFAN ONMLKJ 4;
			goto See;
		Ice:
			XFAN I 5 A_GenericFreezeDeath();
			XFAN I 1 A_FreezeDeathChunks();
			wait;
	}
}

class ShotgunCultistNew : TommyGunCultistNew
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Darkmoon Cultist [shotgun]";

		Health 125; // 40,60,80,100,125
		DamageFactor "Breakfast", 1.25;
		DamageFactor "Cricket", 1.5;
		DamageFactor "Bonk", 1.5;
		painchance 170;
		Painchance "Fist", 255; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Cricket", 255;
		Painchance "Bonk", 255;
		Painchance "Breakfast", 213;
		Translation "80:111=48:79"; // "80:111=48:79"
		DropItem "Shell", 192;
		DropItem "Shell", 12;
	}

	states
	{
		See:
			BCUL A 0;
			BCUL A 0 { bDROPOFF = random(0,1); }
			BCUL AABBCCDD 1
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			XFAN A 0 A_Jump(8,"Shout");
			loop;
		Shout:
			BCUL A 0 A_AlertMonsters(256);
			BCUL A 0 A_StartSound("fanatic/sight");
			Goto See;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			BCUL E 20
			{
				A_FaceTarget();
				user_shotaccuracy = 22.5;
				user_shotzaccuracy = 0.0;
				if (user_charmed) { user_shotaccuracy *= 0.667; user_shotzaccuracy *= 0.667; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(14); user_shotaccuracy = user_shotaccuracy * 13 / 19; user_shotzaccuracy = user_shotzaccuracy * 13 / 19; }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(15); user_shotaccuracy = user_shotaccuracy * 14 / 19; user_shotzaccuracy = user_shotzaccuracy * 14 / 19; }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(16); user_shotaccuracy = user_shotaccuracy * 15 / 19; user_shotzaccuracy = user_shotzaccuracy * 15 / 19; }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(17); user_shotaccuracy = user_shotaccuracy * 16 / 19; user_shotzaccuracy = user_shotzaccuracy * 16 / 19; }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(18); user_shotaccuracy = user_shotaccuracy * 17 / 19; user_shotzaccuracy = user_shotzaccuracy * 17 / 19; }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 10) { A_SetTics(19); user_shotaccuracy = user_shotaccuracy * 18 / 19; user_shotzaccuracy = user_shotzaccuracy * 18 / 19; }
				user_shotaccuracy1 = user_shotaccuracy * -0.5;
				user_shotaccuracy2 = user_shotaccuracy * 0.5;
				user_shotzaccuracy1 = user_shotzaccuracy * -0.5;
				user_shotzaccuracy2 = user_shotzaccuracy * 0.5;
			}
		Shooting:
			BCUL F 10 BRIGHT 
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();
				A_StartSound("shotguy/attack");
				user_pelletsfired = 3;

				A_CustomBulletAttack(user_shotaccuracy, user_shotzaccuracy, user_pelletsfired, Random(4,6) * Random(1,2), "BulletPuff", 0, CBAF_AIMFACING|CBAF_NORANDOM);
			}
			BCUL E 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(random(5,9)); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(random(6,10)); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(random(7,11)); }
				else { A_SetTics(random(8,12)); }
			}
			BCUL E 0 A_MonsterRefire(48,"See");
			loop;
		Frightened:
			BCUL A 0 { bFRIGHTENED = true; }
			BCUL AABBCCDD 3 A_EEChase("Melee","Missile",0,1,3,1,1);
			loop;
		Pain:
			BCUL G 3;
			BCUL G 3 A_EEPain();
			goto See;
		Pain.Bonk:
		Pain.Cricket:
			BCUL G 3;
			BCUL G 3 A_EEPain();
			BCUL GG 3;
			goto See;

		Death:
			BCUL H 5 ThrustThingZ(0,10,0,0);
			BCUL I 5 A_Scream();
			BCUL J 5 A_Fall();
			BCUL KLM 5;
			BCUL M 140;
			TNT1 A 0;
			BCUL N 0 A_Jump(192,"Twitch");
			BCUL N -1;
			stop;
		Twitch:
			BCUL MNMN 5;
			BCUL M 70 A_Jump(80,"Twitch");
			BCUL N 70 A_Jump(80,"Twitch");
			BCUL M 70 A_Jump(80,"Twitch");
			BCUL N -1;
			Stop;
		Raise:
			BCUL N 0 A_UnHideThing();
			BCUL M 5;
			BCUL LKJIH 5;
			goto See;
		Ice:
			BCUL G 5 A_GenericFreezeDeath();
			BCUL G 1 A_FreezeDeathChunks();
			wait;
	}
}

// Magic Using Cultist
class ThrallNew : EECreature
{ 
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Raven Style";
		Tag "Darkmoon Cultist [magician]";

		health 125; // 40,60,80,100,125
		Scale 0.90;
		Speed 8;
		Radius 20;
		Height 56;
		Mass 100;
		PainChance 200;
		DamageFactor "Breakfast", 1.25;
		DamageFactor "Cricket", 1.5;
		DamageFactor "Bonk", 1.5;
		Painchance "Fist", 255; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Cricket", 255;
		Painchance "Bonk", 255;
		Painchance "Breakfast", 250;
		DamageFactor "Zap", 0.75;
		MONSTER;
		+FLOORCLIP;
		+DONTHARMSPECIES;
		-NOGRAVITY;
		-FLOAT;
		SEESOUND "monster/culsit";
		ATTACKSOUND "monster/culatk";
		PAINSOUND "monster/culpai";
		DEATHSOUND "monster/culdth";
		ACTIVESOUND "monster/culact";
		OBITUARY "%o was killed by a lowly cultist mage.";
	}

	states 
	{
		Spawn: 
			CULT A 0 NoDelay ;
			CULT AB 10 A_Look();
			goto Spawn+1;
		See: 
			CULT A 0;
			CULT AABBCCDD 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			CULT A 0
			{
				if (random(1,256) <= 8)
				{
					A_AlertMonsters(256);
					A_StartSound("fanatic/sight");
				}
			}
			loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			CULT EE 5 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }
				A_FaceTarget();
			}
			CULT F 8 BRIGHT 
			{
				A_FaceTarget();
				A_StartSound("monster/culatk");
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) 
				{
					A_SetTics(5); 
					A_SpawnProjectile("ThrallShot1",42,-8,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,-6,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,-4,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,-2,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,-0,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,2,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,4,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,6,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,8,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
				}
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) 
				{
					A_SetTics(6); 
					A_SpawnProjectile("ThrallShot1",42,-6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,-4,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,-2,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",42,2,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",44,4,0,CMF_AIMOFFSET|CMF_BADPITCH,2);
					A_SpawnProjectile("ThrallShot1",42,6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
				}
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) 
				{
					A_SetTics(7); 
					A_SpawnProjectile("ThrallShot1",42,-6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",42,-2,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",42,2,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",42,6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
				}
				else
				{
					A_SpawnProjectile("ThrallShot1",42,-6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
					A_SpawnProjectile("ThrallShot1",42,6,0,CMF_AIMOFFSET|CMF_BADPITCH,0);
				}
			}
			Goto See;
		Pain: 
			CULT G 2;
			CULT G 2 A_EEPain();
			Goto See;
		Pain.Bonk:
		Pain.Cricket:
			CULT G 2;
			CULT G 2 A_EEPain();
			CULT GG 2;
			goto See;

		Death:
			CULT H 8;
			CULT I 8 A_Scream();
			CULT J 4;
			CULT K 4 A_NoBlocking();
			CULT L 4;
			TNT1 A 0;
			CULT M -1;
			Stop;
		XDeath:
			Goto Death;
		Raise: 
			CULT M 5;
			CULT LKJHI 5;
			Goto See;
		Ice:
			CULT G 5 A_GenericFreezeDeath();
			CULT G 1 A_FreezeDeathChunks();
			wait;
	}
}

class ButcherZombieNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Bloated Butcher";

		Health 1090; // 308,436,630,850,1090
		Radius 12;
		Height 56;
		Mass 1250;
		speed 3;
		painchance 4;
		meleerange 48; // 44
		Painchance "Fist", 8; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 16; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Melee", 8;
		Painchance "Chop", 12;
		DamageFactor 0.95;
		RadiusDamageFactor 0.95;
		DamageFactor "Explosive", 0.95;

		DamageFactor "Melee", 0.80;
		DamageFactor "Stomp", 0.80;
		DamageFactor "Trample", 0.80;
		DamageFactor "Fire", 2.25;
		DamageFactor "CherryBomb", 2.25;
		DamageFactor "Spinner", 2.25;
		DamageFactor "BRocket", 2.25;
		DamageFactor "Popper", 2.25;
		DamageFactor "Chop", 3;
		obituary "%o was cut down by a bloated butcher.";
		hitobituary "%o was cut up by a bloated butcher.";
		meleesound "twix";
		seesound "BLOATEDBUTCHER/OTHER";
		painsound "BLOATEDBUTCHER/OTHER";
		deathsound "BLOATEDBUTCHER/DEATH";
		activesound "BLOATEDBUTCHER/OTHER";
		Scale 0.6;
		MONSTER;
		+BOSSDEATH;
		+NOSPLASHALERT;
		+FLOORCLIP;
	}

	states
	{
		Spawn:
			E15W A 0 NoDelay;
			E15W A 10 A_Look();
			goto Spawn+1;
		See:
			E15W A 0;
			E15W AAABBBCCCDDDEEEFFF 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TNT1 A 0 A_Jump(96,"See2");
			loop;
		See2:
			TNT1 A 0;
			E15W A 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W A 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W A 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W B 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W B 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W B 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W C 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W C 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W C 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W D 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W D 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W D 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W E 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W E 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W E 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W F 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			E15W F 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			E15W F 2
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(1); }
				A_EEChase(null,null,0,1,3,1,1);
			}
			TNT1 A 0 A_Jump(96,"See");
			loop;
		Melee:
			TNT1 A 0 A_DynamicMusic();
			E15A B 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_SkelWhoosh();
				A_FaceTarget();
			}
			E15A C 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();
			}
			E15A D 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();

				A_CustomComboAttack("CleaverNew", random(34,40), 2*random(7,13), "skeleton/melee");
			}
			E15A EF 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();
			}
			E15A F 0 { A_ScaleVelocity(0.25); }
			goto See;
		Missile:
			TNT1 A 0 
			{
				A_DynamicMusic();
				A_ScaleVelocity(0.25);
			}
			BYBR E 0 A_JumpIfCloser(128, "Missile1");
			BYBR E 0 A_Jump(64,"Missile1");
			BYBR E 0 A_Jump(256,"Missile2");
			goto See;
		Missile1:
			E15A B 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_SkelWhoosh();
				A_FaceTarget();
			}
			E15A C 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();
			}
			E15A D 5
			{
				A_DynamicMusic();
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();

				A_CustomComboAttack("CleaverNew", random(34,40), 2*random(7,13), "skeleton/melee");
			}
			E15A EF 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();
			}
			E15A F 0 { A_ScaleVelocity(0.25); }
			goto See;
		Missile2:
			E15W J 0 A_FaceTarget();
			E15A GH 5
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();
			}
			E15A I 5 
			{
				A_DynamicMusic();
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(4); }
				A_FaceTarget();

				A_SpawnProjectile("ButcherBarfNew",random(44,52),0,random(-10,10),1,0);
			}
			E15A JIH 4
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(3); }
				A_FaceTarget();
			}
			E15A H 0 { A_ScaleVelocity(0.25); }
			goto See;

		Pain:
			E15A A 1;
			E15A A 1;
			goto See;

		Death:
			E15D A 7 A_Scream();
			E15D B 7;
			E15D C 7;
			E15D D 7 A_NoBlocking();
			E15D D 2 A_StartSound("DSTHUUD");
			E15D EFFFFFFFF 7;
			TNT1 A 0;
			E15D G -1;
			stop;
		Death1:
			BBT2 M 7 A_Scream();
			BBT2 L 0 A_Fall();
			BBT2 M 5 A_XScream();
			BBT2 LLLL 0 A_SpawnDebris ("OrganDebris");
			BBT2 LLL 0 A_SpawnDebris ("Bloodliver");
			BBT2 L 0 A_SpawnDebris ("Hand1");
			BBT2 L 0 A_SpawnItemEx("EyeGuts",random(-8,8),random(-8,8),random(random(0,16),random(32,48)),random(-3,3),random(-2,2),random(-2,2));
			BBT2 M 5 A_SpawnItemEx("FlyingBlood",random(-8,8),random(-8,8),random(random(0,16),random(32,48)),random(-3,3),random(-2,2),random(-2,2));
			BBT2 N 5 A_SpawnItemEx("FlyingBlood",random(-8,8),random(-8,8),random(random(0,16),random(32,48)),random(-3,3),random(-2,2),random(-2,2));
			BBT2 O 5  A_StartSound("DSTHUUD");
			BBT2 PQRSTUV 5 A_SpawnItemEx("FlyingBlood",random(-8,8),random(-8,8),random(random(0,4),random(16,32)),random(-2,2),random(-2,2),random(-2,2));
			BBT2 VWVWVWVWVVWVWVWVWVVWVWVWVWVVWVWVWVWV 5;
			TNT1 A 0;
			BBT2 W -1;
			Stop;
		Raise:
			E15D G 5;
			E15D FDCBA 5;
			goto See;

		XDeath:
			E15X A 6 A_Scream();
			E15X B 5 A_Fall();
			E15X CDEF 4;
			E15X G 25;
			E15X HIJK 6;
			TNT1 A 0;
			E15X L -1;
			Stop;
		Ice:
			E15A A 5 A_GenericFreezeDeath();
			E15A A 1 A_FreezeDeathChunks();
			wait;
	}
}

class BloodZombieNew : EECreature
{
	int user_downedtime;
	int user_downedtimemax;
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Axe Zombie";

		Health 220; // 68,90,130,170,220
		Height 56;
		Radius 12;
		scale 0.45;
		speed 4;
		meleerange 57; // 44
		Mass 500;
		meleedamage 5;
		painchance 4;
		Painchance "Fist", 8; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 16; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Melee", 8; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Chop", 8; // Fist attacks have a +50% chance of stunning an enemy

		DamageFactor 0.75;
		RadiusDamageFactor 0.75;
		DamageFactor "Explosive", 0.75;

		DamageFactor "Fire", 2;
		DamageFactor "CherryBomb", 2;
		DamageFactor "Spinner", 2;
		DamageFactor "BRocket", 2;
		DamageFactor "Popper", 2;
		DamageFactor "Chop", 3;
		MONSTER;
		+BOSSDEATH;
		+FLOORCLIP;
		+DONTOVERLAP;
		+RANDOMIZE;
		+NOSPLASHALERT;
		seesound "BZOMBIEACTIVE";
		Meleesound "TWIX";
		painsound "ZPAIN";
		deathsound "BZOMBIEDIE";
		activesound "BZOMBIEACTIVE";
		obituary "A zombie 'axed' %o a question. :V";
	}
	
	states
	{
		Spawn:
			BZUM A 0 NoDelay;
			BZUM A 10 A_Look();
			goto Spawn+1;
		See:
			AZUM A 0;
			AZUM AAAABBBBCCCCDDDDEEEEFFFF 1
			{
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			loop;
		Melee:
			TNT1 A 0 A_DynamicMusic();
			BZUM AB 4
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }
				A_FaceTarget();
			}
			BZUM CDE 4
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(3); }
				A_FaceTarget();
			}
			BZUM F 4 
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(3); }
				A_FaceTarget();
				A_StartSound("ZAXE");
				
				A_CustomMeleeAttack(2*random(5,13), "TWIX");
			}
			BZUM G 4
			{
				A_ScaleVelocity(0.25);
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(3); }
				A_FaceTarget();
			}
			BZUM G 0 { A_ScaleVelocity(0.25); }
			goto See;

		Pain:    
			AZUM G 0 A_Jump (24, "FallDown");
			AZUM G 1 { if (random(1,512) <= 3) { A_EEPain(); } else { return resolvestate("See"); } return resolvestate(null); }
			goto See;
		FallDown:
			AZUM H 5
			{
				A_EEPain();
				user_downedtimemax = 5 - ((CountInv("MonsterLevel") / random(22,23)) * 1);
				if (user_downedtimemax <= 1) { user_downedtimemax = 1; }
				A_SetTics(user_downedtimemax);
			}
			AZUM H 0
			{
				A_UnSetShootable();
				A_UnSetSolid();
				bNOTARGET = true;
			}
			AZUM IJKL 5
			{
				user_downedtimemax = 5 - ((CountInv("MonsterLevel") / random(22,23)) * 1);
				if (user_downedtimemax <= 1) { user_downedtimemax = 1; }
				A_SetTics(user_downedtimemax);
			}
			AZUM L 175
			{
				user_downedtimemax = 175 - ((CountInv("MonsterLevel") / random(7,8)) * 8);
				if (user_downedtimemax <= 43) { user_downedtimemax = 43; }
				A_SetTics(user_downedtimemax);
			}
		DownCycle:
			AZUM L 20
			{
				user_downedtimemax = 20 - ((CountInv("MonsterLevel") / random(7,8)) * 1);
				if (user_downedtimemax <= 5) { user_downedtimemax = 5; }
				A_SetTics(user_downedtimemax);
			}
			AZUM N 0 A_JumpIfCloser(144, 2);
			AZUM L 0 A_Jump(256, "GetUp");
			AZUM L 0 A_Jump(64, "GetUp");
			loop;
		GetUp:
			AZUM L 10
			{
				user_downedtimemax = 10 - ((CountInv("MonsterLevel") / 15) * 1);
				if (user_downedtimemax <= 5) { user_downedtimemax = 5; }
				A_SetTics(user_downedtimemax);

				A_RadiusThrust(256,128,0);
				A_SetShootable();
				A_SetSolid();
				bNOTARGET = false;
			}
			AZUM MNOPQR 5
			{
				user_downedtimemax = 5 - ((CountInv("MonsterLevel") / random(22,23)) * 1);
				if (user_downedtimemax <= 1) { user_downedtimemax = 1; }
				A_SetTics(user_downedtimemax);
			}
			goto See;

		Death:
			//AZUM H 0 A_JumpIfHealthLower(user_HPXDeathRange2, "Death2");
			AZUM G 7 A_Scream();
			AZUM H 8;
			AZUM I 4;
			AZUM J 4 A_Fall();
			AZUM K 4;
			TNT1 A 0;
			AZUM L -1;
			stop;
		Death2:
			DOTD H 0
			{
				A_StartSound("DSBDSPRY");
				A_Scream();
			}
			TNT1 A 0 A_SpawnProjectile("BloodZombieHead",4,0,random(-200,200),2,random(-10,-30));
			AZUM SSS 2 A_ThrowGrenade("FlyingBlood",5,5+random(-3,3),10+random(-4,4),0);
			AZUM T 2 A_ThrowGrenade("FlyingBlood",5,5+random(-3,3),10+random(-4,4),0);
			AZUM U 2 A_ThrowGrenade("FlyingBlood",0,5+random(-3,3),10+random(-4,4),0);
			AZUM H 0 A_Fall();
			AZUM V 2 A_ThrowGrenade("FlyingBlood",-5,5+random(-3,3),10+random(-4,4),0);
			AZUM W 2 A_ThrowGrenade("FlyingBlood",-10,5+random(-3,3),10+random(-4,4),0);
			AZUM X 2 A_ThrowGrenade("FlyingBlood",-15,5+random(-3,3),10+random(-4,4),0);
			AZUM Y 2 A_ThrowGrenade("FlyingBlood",-20,5+random(-3,3),10+random(-4,4),0);
			AZUM H 0 A_StartSound("DSBDSPRY");
			AZUM Z 2 A_ThrowGrenade("FlyingBlood",-20,5+random(-3,3),10+random(-4,4),0);
			AZUM H 0 A_StartSound("DSBDSPRY");
			AZUM Z 2 A_ThrowGrenade("FlyingBlood",-20,5+random(-3,3),5+random(-4,4),0);
			TNT1 A 0;
			AZUM Z -1;
			stop;

		XDeath:
			XZUM A 0 A_Scream();
			XZUM A 6;
			XZUM L 0 A_Fall();
			XZUM BCDEFGH 3;
			TNT1 A 0;
			XZUM I -1;
			Stop;

		Raise:
			AZUM M 5;
			AZUM NOPQR 5;
			goto See;
		Ice:
			AZUM G 5 A_GenericFreezeDeath();
			AZUM G 1 A_FreezeDeathChunks();
			wait;
	}
}

class MiniSpiderNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Spider [smaller]";
		
		health 38; // 15
		Speed 15; // 10
		Radius 7;
		Height 15;
		Health 15;
		Scale 0.25;
		Translation 0;
		Damage 0;
		MeleeDamage 1;
		MONSTER;
		+FLOORCLIP;
		seesound "littlespider/sight";
		attacksound "littlespider/attack";
		painsound "littlespider/pain";
		deathsound "littlespider/death";
		activesound "littlespider/sight";
		meleesound "littlespider/pain";
		DamageFactor "Suck", 4;
		DamageFactor "Cricket", 2;
		DamageFactor "Bonk", 2;
		DamageFactor "Breakfast", 1.25;
		DamageFactor "Dust", 4;
	}
	
	States
	{
		Spawn:
			MNTR A 0 NoDelay;
			MNTR AB 5 A_Look();
			goto Spawn+1;
		See:
			MNTR A 0;
			MNTR ABCD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(1); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Melee:
			TNT1 A 0 A_DynamicMusic();
			MNTR VW 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }
				A_FaceTarget();
			}
			MNTR X 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }

				A_SpawnProjectile("SpiderBiteProj",16,0,0,CMF_CHECKTARGETDEAD,0,AAPTR_TARGET); //A_MeleeAttack;
			}
			Goto See;

		Pain:
			Goto See;
		XDeath:
		Death:
			MNTS F 4;
			MNTS E 4 A_Scream();
			MNTS D 4;
			MNTS C 4 A_NoBlocking();
			MNTS B 4;
			TNT1 A 0;
			MNTS A -1 A_BossDeath();
			Stop;
		Ice:
			MNTR A 5 A_GenericFreezeDeath();
			MNTR A 1 A_FreezeDeathChunks();
			wait;
	}
}

class LargeSpiderNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Spider [huge]";

		Health 525; // 150
		Speed 15;
		Damage 0;
		Radius 14;
		Height 30;
		Health 150;
		Scale 0.50;
		Translation 1;
		MeleeDamage 2;
		MeleeRange 66;
		DamageFactor 0.75;
		RadiusDamageFactor 0.75;
		DamageFactor "Explosive", 0.75;
		MONSTER;
		+FLOORCLIP;
		seesound "littlespider/sight";
		attacksound "littlespider/attack";
		painsound "littlespider/pain";
		deathsound "littlespider/death";
		activesound "littlespider/sight";
		meleesound "littlespider/pain";
		DamageFactor "Suck", 4;
		DamageFactor "Cricket", 2;
		DamageFactor "Bonk", 2;
		DamageFactor "Breakfast", 1.25;
		DamageFactor "Dust", 4;
	}

	States
	{
		Spawn:
			MNTR A 0 NoDelay;
			MNTR AB 10 A_Look();
			goto Spawn+1;
		See:
			MNTR A 0;
			MNTR ABCD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(1); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			MNTR A 10 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 100) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 80) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();
			}
			MNTR A 0 A_SkullAttack();
			MNTR ABCD 2;
			Goto Missile+2;
		Melee:
			TNT1 A 0 A_DynamicMusic();
			MNTR VW 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }
				A_FaceTarget();
			}
			MNTR X 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(3); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(4); }

				A_SpawnProjectile("SpiderBiteProj2",32,0,CMF_CHECKTARGETDEAD,0,AAPTR_TARGET); //A_MeleeAttack;
			}
			Goto See;

		Pain:
			Goto See;
		Death:
			MNTS F 5;
			MNTS E 5 A_Scream();
			MNTS D 5;
			MNTS C 5 A_NoBlocking();
			MNTS B 5;
			TNT1 A 0;
			MNTS A -1 A_BossDeath();
			Stop;
		Ice:
			MNTR A 5 A_GenericFreezeDeath();
			MNTR A 1 A_FreezeDeathChunks();
			wait;
	}
}

class ThamuzApocalypseDefendMode : PowerProtection
{
	default
	{
		damagefactor "Normal", 0.20;
		damagefactor "Cricket", 0.75;
		damagefactor "Bonk", 0.75;
		damagefactor "Dust", 1.0;
		damagefactor "Zap", 0.5;
		inventory.icon "";
		Powerup.Duration 2147483646;
	}
}

class ThamuzNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Boss";
		Tag "Thamuz, The Dark God";

		Radius 40;
		Height 110;
		Bloodcolor "00 aa 00";
		Scale 1.1;
		Health 32000;
		Mass 40000;
		Speed 16;
		Scale 1.1;
		MinMissileChance 5;
		painchance 35;
		painchance "Zap", 140;
		Painchance "Fist", 52; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 87; // Kick attacks have a +150% chance of stunning an enemy

		DamageFactor 0.375;
		RadiusDamageFactor 0.375;
		DamageFactor "Explosive", 0.375;
		DamageFactor "Zap", 2.0;
		MONSTER;
		+BOSS;
		+NORADIUSDMG;
		+FLOORCLIP;
		+MISSILEEVENMORE;
		+MISSILEMORE;
		SEESOUND "Thamuz/Idlesight";
		PAINSOUND "Thamuz/Pain";
		DEATHSOUND "Thamuz/death";
		ACTIVESOUND "Thamuz/Idlesight";
		OBITUARY "%o fell before the might of Thamuz, the Dark God.";
		RenderStyle "Translucent";
		Alpha 0.95;
	}

	states
	{
		ResetLevel:
			DCYB A 1 A_Look();
			DCYB A 1;
			DCYB A 1 { user_ressurrectstr += random(15,30); }
			DCYB A 1;
			goto Spawn+1;
		Spawn:
			DCYB A 0 NoDelay;
			DCYB A 10 A_Look();
			goto Spawn+1;
		See:
			DCYB A 0 Thing_ChangeTID(0,1222);
			DCYB A 0;
			DCYB AA 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostA",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB BB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostB",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB CC 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostC",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB DD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostD",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			DCYB A 0 A_Jump(160,"ApocalypseAtk");
			DCYB AEE 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(7); }
				A_FaceTarget();
			}
			DCYB F 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();

				A_SpawnProjectile("DCBMiss1",56,-25,0);
			}
			DCYB E 15
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(9); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(62,63)) { A_SetTics(10); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(11); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(12); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 25) { A_SetTics(13); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(12,13)) { A_SetTics(14); }
				A_FaceTarget();
			}
			Goto See;
		ApocalypseAtk:
			DCYB A 0 A_Jump(160,"Barrage");
			DCYB G 20
			{
				A_DynamicMusic();
				A_SetInventory("ThamuzApocalypseDefendMode",1); // A_SetInvulnerable
				bNOPAIN = true;
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(14); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(15); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(16); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(17); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(18); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 10) { A_SetTics(19); }
				A_StartSound("Apocalypse/cast");

				for (user_barragecounter = 0; user_barragecounter < 18; user_barragecounter++)
				{
					A_SpawnProjectile("DCBMiss3",50,0,user_barragecounter*20);
				}
			}
			DCYB G 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			DCYB G 0 A_Jump(64,5);
			DCYB G 0 A_Jump(64,8);
			DCYB GGGGGGGG 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			DCYB G 10
			{
				A_DynamicMusic();
				bNOPAIN = false;
				A_SetInventory("ThamuzApocalypseDefendMode",0); // A_UnsetInvulnerable
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			Goto See;
		Barrage:
			DCYB AE 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				user_barragecounter = 0;
				user_shotsfired = 0;
				user_shotsfiredmax = 10 + CountInv("MonsterLevel") / 10;
			}
		BarrageStart:
			DCYB EF 4
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 105) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(52,53)) { A_SetTics(3); }
				A_FaceTarget();
				user_barragecounter += 1;
				if (user_barragecounter == 2) 
				{
					A_SpawnProjectile("DCBMiss2",56,-25,0);
					user_barragecounter = 0; 
					user_shotsfired += 1;
				}
			}
			DCYB F 0
			{
				if (user_shotsfired >= user_shotsfiredmax) { return resolvestate("See"); }
				return resolvestate(null);
			}
			loop;

		Pain:
			DCYB A 0 A_SetInventory("ThamuzApocalypseDefendMode",0);
			DCYB G 2;
			DCYB G 2 A_EEPain();
			Goto See;
		Death:
			DCYB H 5;
			DCYB I 5 A_Scream();
			DCYB A 0 A_SpawnProjectile("BDS",0,0,0);
			DCYB JKLMNO 5;
			TNT1 A 0;
			DCYB P -1 A_NoBlocking();
			Stop;
		Ice:
			Goto Death;
	}
}

class TchernobogNew : ThamuzNew
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Boss";
		Tag "Tchernobog, The One That Binds?";

		Radius 40;
		Height 110;
		Health 21333;
		RenderStyle "Translucent";
		Alpha 0.95;
		painchance 35;
		painchance "Zap", 52;
		painchance "Cricket", 87;
		DamageFactor 0.25;
		RadiusDamageFactor 0.25;
		DamageFactor "Explosive", 0.25;
		DamageFactor "Zap", 0.667;
		DamageFactor "Cricket", 2.5;
		Mass 80000;
		Speed 16;
		OBITUARY "%o fell before the might of The One That Binds.";
		Bloodcolor "aa 00 00";
	}
	
	states
	{
		ResetLevel:
			TCHR A 1 A_Look();
			TCHR A 1;
			TCHR A 1 { user_ressurrectstr += random(15,30); }
			TCHR A 1; 
			goto Spawn+1;
		Spawn:
			TCHR A 0 NoDelay;
			TCHR A 10 A_Look();
			goto Spawn+1;
		See:
			TCHR A 0 Thing_ChangeTID(0,1222);
			TCHR A 0;
			TCHR AA 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostA",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR BB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostB",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR CC 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostC",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR DD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostD",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			TCHR A 0 A_Jump(160,"ApocalypseAtk");
			TCHR AEE 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(7); }
				A_FaceTarget();
			}
			TCHR F 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();

				A_SpawnProjectile("DCBMiss1",80,0,0);
			}
			TCHR E 15
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(9); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(62,63)) { A_SetTics(10); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(11); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(12); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 25) { A_SetTics(13); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(12,13)) { A_SetTics(14); }
				A_FaceTarget();
			}
			Goto See;
		ApocalypseAtk:
			TCHR A 0 A_Jump(160,"Barrage");
			TCHR G 20
			{
				A_DynamicMusic();
				A_SetInventory("ThamuzApocalypseDefendMode",1); // A_SetInvulnerable
				bNOPAIN = true;
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(14); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(15); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(16); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(17); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(18); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 10) { A_SetTics(19); }
				A_StartSound("Apocalypse/cast");
				
				for (user_barragecounter = 0; user_barragecounter < 18; user_barragecounter++)
				{
					A_SpawnProjectile("DCBMiss3",36,0,user_barragecounter*20);
				}
			}
			TCHR G 0 A_Jump(64,5);
			TCHR G 0 A_Jump(64,8);
			TCHR GGGGGGGG 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			TCHR G 10
			{
				A_DynamicMusic();
				bNOPAIN = false;
				A_SetInventory("ThamuzApocalypseDefendMode",0); // A_UnsetInvulnerable
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			Goto See;
		Barrage:
			TCHR AE 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				user_barragecounter = 0;
				user_shotsfired = 0;
				user_shotsfiredmax = 10 + CountInv("MonsterLevel") / 10;
			}
		BarrageStart:
			TCHR FF 4
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 105) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(52,53)) { A_SetTics(3); }
				A_FaceTarget();
				user_barragecounter += 1;
				if (user_barragecounter == 2) 
				{
					A_SpawnProjectile("DCBMiss2",80,0,0);
					user_barragecounter = 0; 
					user_shotsfired += 1;
				}
			}
			TCHR F 0
			{
				if (user_shotsfired >= user_shotsfiredmax) { return resolvestate("See"); }
				return resolvestate(null);
			}
			loop;
		Pain:
			TCHR A 0 A_SetInventory("ThamuzApocalypseDefendMode",0);
			TCHR G 2;
			TCHR G 2 A_EEPain();
			Goto See;
		Death:
			TCHR Q 5;
			TCHR Q 5 A_Scream();
			TCHR A 0 A_SpawnProjectile("BDS",0,0,0);
			TCHR QRSTUVWX 5;
			TNT1 A 0;
			TNT1 A -1 A_NoBlocking;
			Stop;
		Ice:
			Goto Death;
	}
}

class HellHoundNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Blood Style";
		Tag "Hell Hound";

		health 750;
		Speed 16;
		Radius 30;
		Height 50;
		Mass 500;
		MeleeDamage 7;
		PainChance 128;
		Painchance "Fist", 192; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Ice", 255;
		Painchance "Bonk", 255;
		DamageFactor "Bonk", 2.25;
		DamageFactor 0.875;
		RadiusDamageFactor 0.875;
		DamageFactor "Explosive", 0.875;
		DamageFactor "Ice", 4;
		MONSTER;
		+FLOORCLIP;
		+FIRERESIST;
		+DONTHARMSPECIES;
		OBITUARY "%o was burned alive by a hellhound.";
		HITOBITUARY "A hellhound had %o for dinner.";
		SEESOUND "monster/dogsit";
		ATTACKSOUND "monster/dogatk";
		MELEESOUND "monster/dogbit";
		PAINSOUND "monster/dogpai";
		DEATHSOUND "monster/dogdth";
		ACTIVESOUND "monster/dogact";
	}

	states 
	{
		ResetLevel:
			HDOG A 1 A_Look();
			HDOG A 1;
			HDOG A 1 
			{
				user_ressurrectstr += random(5,10);
			}
			HDOG A 1;
			goto Spawn+1;
		Spawn: 
			HDOG A 0 NoDelay;
			HDOG AA 10 A_Look(); 
			goto Spawn+1;
		See: 
			HDOG A 0;
			HDOG AAAABBBBCCCCDDDDEEEEFFFF 1
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			loop;
		Melee: 
			TNT1 A 0 A_DynamicMusic();
			HDOG GH 6
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
			}
			HDOG I 6 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				
				A_CustomMeleeAttack(7*random(1,8),"monster/dogbit");
			}
			Goto See;
		Missile:
			TNT1 A 0 
			{
				A_DynamicMusic();
				user_shotsfired = 0;
				user_shotsfiredmax = 12 + (CountInv("MonsterLevel") / 7.5);
			}
			HDOG G 0 A_JumpIfCloser(256,2);
			HDOG G 0;
			Goto See;
			HDOG G 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 15) { A_SetTics(9); }
				A_FaceTarget();
			}
		BreathLoop:
			HDOG H 1 
			{
				A_FaceTarget();
				
				A_SpawnProjectile("DogFireNew",28,0,0,0,0);
				user_shotsfired += 1;
			}
			HDOG H 0
			{
				if (user_shotsfired > user_shotsfiredmax) { return resolvestate("BreathEnd"); }
				return resolvestate(null);
			}
			loop;
		BreathEnd:
			HDOG I 6 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
			}
			Goto See;
		Pain: 
			HDOG J 2;
			HDOG J 2 A_EEPain();
			Goto See;
		Pain.Bonk:
			HDOG J 2;
			HDOG J 2 A_EEPain();
			HDOG JJ 2; 
			Goto See;
		Pain.Ice: 
			HDOG J 2; 
			HDOG J 2 A_EEPain();
			HDOG JJJJ 2;
			Goto See;

		Death:
			HDOG K 8;
			HDOG L 8 A_Scream();
			HDOG M 4;
			HDOG N 4 A_NoBlocking();
			HDOG OP 4;
			TNT1 A 0;
			HDOG Q -1; 
			Stop;
		Raise: 
			HDOG Q 5;
			HDOG PONMLK 5;
			Goto See;
		Ice:
			HDOG J 5 A_GenericFreezeDeath();
			HDOG J 1 A_FreezeDeathChunks();
			wait;
	}
}

class ApprenticeSheenMode : PowerProtection
{
	default
	{
		damagefactor "Normal", 0.125;
		damagefactor "Cricket", 0.5;
		damagefactor "Bonk", 0.5;
		damagefactor "Suck", 2.0;
		radiusdamagefactor 0.125;
		damagefactor "Explosive", 0.125;
		inventory.icon "";
		Powerup.Duration 2147483646;
	}
}

class ApprenticeNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Raven Style";
		Tag "Darkmoon Grand Apprentice";
		
		Health 1250;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 100;
		Painchance "Fist", 150; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 250; // Kick attacks have a +150% chance of stunning an enemy

		DamageFactor 0.5;
		RadiusDamageFactor 0.5;
		DamageFactor "Explosive", 0.5;
		DamageFactor "Zap", 0.5;
		MONSTER;
		+FloorClip;
		+NoGravity;
		+Float;
		SEESOUND "wizard/sight";
		PAINSOUND "wizard/pain";
		DEATHSOUND "wizard/death";
		ACTIVESOUND "wizard/active";
		OBITUARY "%o was spooked by an Apprentice of Darkmoon.";
	}

	states
	{
		Spawn:
			APDP A 0 NoDelay;
			APDP AB 10 A_Look();
			goto Spawn+1;
		See:
			APDP A 0;
			APDP A 0
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP AABB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 0 A_Jump(128,"Missile2");
			APDP C 0 A_Jump(64,"Missile3");
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			Goto See;
		Missile2:
			APDP CCCCCCCCC 1 { A_SetTranslucent(alpha-0.1,0); A_FaceTarget(); }
			APDP D 1
			{
				bNOPAIN = true;
				A_SetInventory("ApprenticeSheenMode",1);
				A_SetTranslucent(0.1,0);
			}
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP BABABABAB 1 { A_SetTranslucent(alpha+0.1,0); A_FaceTarget(); }
			APDP A 1
			{
				A_FaceTarget();
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1.0,0);
			}
			Goto See;
		Missile3:
			APDP D 4
			{
				A_DynamicMusic();
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("SuperFireBlast",15,0,0);
			}
			Goto See;
		Pain:
			APDP E 0 // A_UnsetInvulnerable
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP E 2;
			APDP E 2 A_EEPain();
			Goto See;

		Death:
			APDP E 0 // A_UnsetInvulnerable
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP E 4;
			APDP F 4;
			APDP G 3 A_Scream();
			APDP H 3 A_SpawnProjectile("AoDGhost",8,0,0);
			APDP I 3 A_Fall();
			APDP JKL 2;
			APDP M -1;
			Stop;
		Raise:
			APDP M 8;
			APDP L 8;
			APDP KJI 6;
			Goto See;
		XDeath:
			goto Death;
		Ice:
			APDP E 5 A_GenericFreezeDeath();
			APDP E 1 A_FreezeDeathChunks();
			wait;
	}
}

