class ThamuzApocalypseDefendMode : PowerProtection
{
	default
	{
		damagefactor "Normal", 0.20;
		damagefactor "Cricket", 0.75;
		damagefactor "Bonk", 0.75;
		damagefactor "Dust", 1.0;
		damagefactor "Zap", 0.5;
		inventory.icon "";
		Powerup.Duration 2147483646;
	}
}

class ThamuzNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Boss";
		Tag "Thamuz, The Dark God";

		Radius 40;
		Height 110;
		Bloodcolor "00 aa 00";
		Scale 1.1;
		Health 32000;
		Mass 40000;
		Speed 16;
		Scale 1.1;
		MinMissileChance 5;
		painchance 35;
		painchance "Zap", 140;
		Painchance "Fist", 52; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 87; // Kick attacks have a +150% chance of stunning an enemy

		DamageFactor 0.375;
		RadiusDamageFactor 0.375;
		DamageFactor "Explosive", 0.375;
		DamageFactor "Zap", 2.0;
		MONSTER;
		+BOSS;
		+NORADIUSDMG;
		+FLOORCLIP;
		+MISSILEEVENMORE;
		+MISSILEMORE;
		SEESOUND "Thamuz/Idlesight";
		PAINSOUND "Thamuz/Pain";
		DEATHSOUND "Thamuz/death";
		ACTIVESOUND "Thamuz/Idlesight";
		OBITUARY "%o fell before the might of Thamuz, the Dark God.";
		RenderStyle "Translucent";
		Alpha 0.95;
	}

	states
	{
		ResetLevel:
			DCYB A 1 A_Look();
			DCYB A 1;
			DCYB A 1 { user_ressurrectstr += random(15,30); }
			DCYB A 1;
			goto Spawn+1;
		Spawn:
			DCYB A 0 NoDelay;
			DCYB A 10 A_Look();
			goto Spawn+1;
		See:
			DCYB A 0 Thing_ChangeTID(0,1222);
			DCYB A 0;
			DCYB AA 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostA",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB BB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostB",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB CC 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostC",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			DCYB DD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("DarkCyberGhostD",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			DCYB A 0 A_Jump(160,"ApocalypseAtk");
			DCYB AEE 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(7); }
				A_FaceTarget();
			}
			DCYB F 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();

				A_SpawnProjectile("DCBMiss1",56,-25,0);
			}
			DCYB E 15
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(9); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(62,63)) { A_SetTics(10); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(11); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(12); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 25) { A_SetTics(13); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(12,13)) { A_SetTics(14); }
				A_FaceTarget();
			}
			Goto See;
		ApocalypseAtk:
			DCYB A 0 A_Jump(160,"Barrage");
			DCYB G 20
			{
				A_DynamicMusic();
				A_SetInventory("ThamuzApocalypseDefendMode",1); // A_SetInvulnerable
				bNOPAIN = true;
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(14); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(15); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(16); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(17); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(18); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 10) { A_SetTics(19); }
				A_StartSound("Apocalypse/cast");

				for (user_barragecounter = 0; user_barragecounter < 18; user_barragecounter++)
				{
					A_SpawnProjectile("DCBMiss3",50,0,user_barragecounter*20);
				}
			}
			DCYB G 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			DCYB G 0 A_Jump(64,5);
			DCYB G 0 A_Jump(64,8);
			DCYB GGGGGGGG 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			DCYB G 10
			{
				A_DynamicMusic();
				bNOPAIN = false;
				A_SetInventory("ThamuzApocalypseDefendMode",0); // A_UnsetInvulnerable
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			Goto See;
		Barrage:
			DCYB AE 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				user_barragecounter = 0;
				user_shotsfired = 0;
				user_shotsfiredmax = 10 + CountInv("MonsterLevel") / 10;
			}
		BarrageStart:
			DCYB EF 4
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 105) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(52,53)) { A_SetTics(3); }
				A_FaceTarget();
				user_barragecounter += 1;
				if (user_barragecounter == 2) 
				{
					A_SpawnProjectile("DCBMiss2",56,-25,0);
					user_barragecounter = 0; 
					user_shotsfired += 1;
				}
			}
			DCYB F 0
			{
				if (user_shotsfired >= user_shotsfiredmax) { return resolvestate("See"); }
				return resolvestate(null);
			}
			loop;

		Pain:
			DCYB A 0 A_SetInventory("ThamuzApocalypseDefendMode",0);
			DCYB G 2;
			DCYB G 2 A_EEPain();
			Goto See;
		Death:
			DCYB H 5;
			DCYB I 5 A_Scream();
			DCYB A 0 A_SpawnProjectile("BDS",0,0,0);
			DCYB JKLMNO 5;
			TNT1 A 0;
			DCYB P -1 A_NoBlocking();
			Stop;
		Ice:
			Goto Death;
	}
}

class TchernobogNew : ThamuzNew
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Boss";
		Tag "Tchernobog, The One That Binds?";

		Radius 40;
		Height 110;
		Health 21333;
		RenderStyle "Translucent";
		Alpha 0.95;
		painchance 35;
		painchance "Zap", 52;
		painchance "Cricket", 87;
		DamageFactor 0.25;
		RadiusDamageFactor 0.25;
		DamageFactor "Explosive", 0.25;
		DamageFactor "Zap", 0.667;
		DamageFactor "Cricket", 2.5;
		Mass 80000;
		Speed 16;
		OBITUARY "%o fell before the might of The One That Binds.";
		Bloodcolor "aa 00 00";
	}
	
	states
	{
		ResetLevel:
			TCHR A 1 A_Look();
			TCHR A 1;
			TCHR A 1 { user_ressurrectstr += random(15,30); }
			TCHR A 1; 
			goto Spawn+1;
		Spawn:
			TCHR A 0 NoDelay;
			TCHR A 10 A_Look();
			goto Spawn+1;
		See:
			TCHR A 0 Thing_ChangeTID(0,1222);
			TCHR A 0;
			TCHR AA 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostA",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR BB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostB",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR CC 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostC",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			TCHR DD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_SpawnItem("TchernoGhostD",0,0);
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			TCHR A 0 A_Jump(160,"ApocalypseAtk");
			TCHR AEE 5
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(7); }
				A_FaceTarget();
			}
			TCHR F 10
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
				A_FaceTarget();

				A_SpawnProjectile("DCBMiss1",80,0,0);
			}
			TCHR E 15
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(9); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(62,63)) { A_SetTics(10); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(11); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(12); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 25) { A_SetTics(13); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(12,13)) { A_SetTics(14); }
				A_FaceTarget();
			}
			Goto See;
		ApocalypseAtk:
			TCHR A 0 A_Jump(160,"Barrage");
			TCHR G 20
			{
				A_DynamicMusic();
				A_SetInventory("ThamuzApocalypseDefendMode",1); // A_SetInvulnerable
				bNOPAIN = true;
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(14); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 50) { A_SetTics(15); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(16); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { A_SetTics(17); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(18); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 10) { A_SetTics(19); }
				A_StartSound("Apocalypse/cast");
				
				for (user_barragecounter = 0; user_barragecounter < 18; user_barragecounter++)
				{
					A_SpawnProjectile("DCBMiss3",36,0,user_barragecounter*20);
				}
			}
			TCHR G 0 A_Jump(64,5);
			TCHR G 0 A_Jump(64,8);
			TCHR GGGGGGGG 10
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			TCHR G 10
			{
				A_DynamicMusic();
				bNOPAIN = false;
				A_SetInventory("ThamuzApocalypseDefendMode",0); // A_UnsetInvulnerable
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 40) { A_SetTics(8); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 20) { A_SetTics(9); }
			}
			Goto See;
		Barrage:
			TCHR AE 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				user_barragecounter = 0;
				user_shotsfired = 0;
				user_shotsfiredmax = 10 + CountInv("MonsterLevel") / 10;
			}
		BarrageStart:
			TCHR FF 4
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 105) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(52,53)) { A_SetTics(3); }
				A_FaceTarget();
				user_barragecounter += 1;
				if (user_barragecounter == 2) 
				{
					A_SpawnProjectile("DCBMiss2",80,0,0);
					user_barragecounter = 0; 
					user_shotsfired += 1;
				}
			}
			TCHR F 0
			{
				if (user_shotsfired >= user_shotsfiredmax) { return resolvestate("See"); }
				return resolvestate(null);
			}
			loop;
		Pain:
			TCHR A 0 A_SetInventory("ThamuzApocalypseDefendMode",0);
			TCHR G 2;
			TCHR G 2 A_EEPain();
			Goto See;
		Death:
			TCHR Q 5;
			TCHR Q 5 A_Scream();
			TCHR A 0 A_SpawnProjectile("BDS",0,0,0);
			TCHR QRSTUVWX 5;
			TNT1 A 0;
			TNT1 A -1 A_NoBlocking;
			Stop;
		Ice:
			Goto Death;
	}
}

class ApprenticeSheenMode : PowerProtection
{
	default
	{
		damagefactor "Normal", 0.125;
		damagefactor "Cricket", 0.5;
		damagefactor "Bonk", 0.5;
		damagefactor "Suck", 2.0;
		radiusdamagefactor 0.125;
		damagefactor "Explosive", 0.125;
		inventory.icon "";
		Powerup.Duration 2147483646;
	}
}

class ApprenticeNew : EECreature
{
	default
	{
		//$Angled;
		//$Color 12;
		//$Category "TCOTD:A Monsters/Raven Style";
		Tag "Darkmoon Grand Apprentice";
		
		Health 1250;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 100;
		Painchance "Fist", 150; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 250; // Kick attacks have a +150% chance of stunning an enemy

		DamageFactor 0.5;
		RadiusDamageFactor 0.5;
		DamageFactor "Explosive", 0.5;
		DamageFactor "Zap", 0.5;
		MONSTER;
		+FloorClip;
		+NoGravity;
		+Float;
		SEESOUND "wizard/sight";
		PAINSOUND "wizard/pain";
		DEATHSOUND "wizard/death";
		ACTIVESOUND "wizard/active";
		OBITUARY "%o was spooked by an Apprentice of Darkmoon.";
	}

	states
	{
		Spawn:
			APDP A 0 NoDelay;
			APDP AB 10 A_Look();
			goto Spawn+1;
		See:
			APDP A 0;
			APDP A 0
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP AABB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 30) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 45) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			TNT1 A 0 A_DynamicMusic();
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 2 A_SetTranslucent(frandom(0.34,0.67),0);
			APDP C 2 A_SetTranslucent(1.0,0);
			APDP C 0 A_Jump(128,"Missile2");
			APDP C 0 A_Jump(64,"Missile3");
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			Goto See;
		Missile2:
			APDP CCCCCCCCC 1 { A_SetTranslucent(alpha-0.1,0); A_FaceTarget(); }
			APDP D 1
			{
				bNOPAIN = true;
				A_SetInventory("ApprenticeSheenMode",1);
				A_SetTranslucent(0.1,0);
			}
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP CCCC 2 { A_SetTranslucent(alpha+0.08,0); A_FaceTarget(); }
			APDP D 6
			{
				A_DynamicMusic();
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 75) { A_SetTics(4); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > random(37,38)) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("wizard/attack");
				
				A_SpawnProjectile("FireBlast",30,-10,-4);
				A_SpawnProjectile("FireBlast",30,0,0);
				A_SpawnProjectile("FireBlast",30,10,4);
			}
			APDP CCCC 2 { A_SetTranslucent(alpha-0.08,0); A_FaceTarget(); }
			APDP CCCCCCCCCCCCCCCC 1 { A_EEWander(0,1,3,1,1); A_FaceTarget(); }
			APDP BABABABAB 1 { A_SetTranslucent(alpha+0.1,0); A_FaceTarget(); }
			APDP A 1
			{
				A_FaceTarget();
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1.0,0);
			}
			Goto See;
		Missile3:
			APDP D 4
			{
				A_DynamicMusic();
				A_FaceTarget();
				A_StartSound("wizard/attack");

				A_SpawnProjectile("SuperFireBlast",15,0,0);
			}
			Goto See;
		Pain:
			APDP E 0 // A_UnsetInvulnerable
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP E 2;
			APDP E 2 A_EEPain();
			Goto See;

		Death:
			APDP E 0 // A_UnsetInvulnerable
			{
				bNOPAIN = false;
				A_SetInventory("ApprenticeSheenMode",0);
				A_SetTranslucent(1,0);
			}
			APDP E 4;
			APDP F 4;
			APDP G 3 A_Scream();
			APDP H 3 A_SpawnProjectile("AoDGhost",8,0,0);
			APDP I 3 A_Fall();
			APDP JKL 2;
			APDP M -1;
			Stop;
		Raise:
			APDP M 8;
			APDP L 8;
			APDP KJI 6;
			Goto See;
		XDeath:
			goto Death;
		Ice:
			APDP E 5 A_GenericFreezeDeath();
			APDP E 1 A_FreezeDeathChunks();
			wait;
	}
}

