// The Big Clown Boi Himself :V
class PennywiseBoss : EEUniqueBoss // 3672
{
	default
	{
		//$Angled
		//$Color 12
		//$Category "Happy Time Circus/Bosses"
		Tag "Pennywise The Dancing Clown";
	
		Health 45000;
		Radius 40;
		Height 112;
		Speed 8;
		MONSTER;
		MinMissileChance 40;
		scale 1.25;
		Mass 135000;
		PainChance 224;
		Painchance "Fist", 255; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		PainChance "Zap", 252;
		PainChance "Melee", 252;
		PainChance "Deadlight", 256;
		DamageFactor 0.667;
		RadiusDamageFactor 0.667;
		DamageFactor "Explosive", 0.667;
	
		DamageFactor "Zap", 2.5;
		DamageFactor "Melee", 1.5;
		DamageFactor "Stomp", 1.5;
		DamageFactor "Trample", 1.5;
		DamageFactor "Deadlight", 7.5;
		+BOSS;
		+FLOORCLIP;
		+FULLVOLACTIVE;
		+NOTARGET;
		+LOOKALLAROUND;
		+NODAMAGETHRUST;
		-NORADIUSDMG;
		SeeSound "";
		PainSound "PENHURT";
		DeathSound "pwise/death";
		ActiveSound "ITACTIVE";
		MeleeSound "imp/melee";
		Obituary "%o was killed by Pennywise the Dancing Clown.";
		HitObituary "%o was killed by Pennywise the Dancing Clown.";
		MissileHeight 96;
		MissileType "PennySeeker";
	}
	int regentimer;
	int degentimer;
	
	override void Tick()
	{
		if (!CountInv("PennywiseNotShield"))
		{
			if (health < (SpawnHealth() + Stamina))
			{
				if (CountInv("PWDefenseBuff")) regentimer += 9;
				regentimer += 3;
				if (regentimer >= 32)
				{
					health++;
					if (health > (SpawnHealth() + Stamina)) health = (SpawnHealth() + Stamina);
					regentimer -= 32;
				}
			}
		}
		else
		{
			if (health > ((SpawnHealth() + Stamina) * 0.01))
			{
				degentimer += 12;
				if (CountInv("PWDefenseBuff")) degentimer -= 9;
				if (degentimer >= 32)
				{
					health--;
					if (health < ((SpawnHealth() + Stamina) * 0.01)) health = ((SpawnHealth() + Stamina) * 0.01);
					degentimer -= 32;
				}
			}
		}
		
		super.Tick();
	}
	
	States
	{
		Spawn:
			PLIT J 0 NoDelay;
			PLIT J 10 A_Look();
			goto Spawn+1;
		See:
			PLIT QPONMLJKIHGFEDCB 2;
			goto See2;
		See2:
			PENY AABB 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
				A_SetInventory("PennywiseShield",1);
				A_SetInventory("PennywiseNotShield",0);
				if (CountInv("PWDefenseBuff")) A_SetTics(2);
			}
			PENY CCDD 3
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { bAVOIDMELEE = true; }
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(2); }
				A_EEChase("Melee","Missile",0,1,3,1,1);
				A_SetInventory("PennywiseShield",1);
				A_SetInventory("PennywiseNotShield",0);
				if (CountInv("PWDefenseBuff")) A_SetTics(2);
			}
			PENY A 0
			{
				if (CountInv("PWDefenseBuff"))
				{
					A_QuakeEx(random(0,1),random(0,1),random(0,2),random(5,8),0,512,"",QF_SCALEDOWN);
				}
			}
			loop;
		Melee:
			PENY E 1  
			{
				A_SetInventory("PennywiseShield",0);
				A_FaceTarget();
			}
			PENY E 1
			{
				A_SetInventory("PennywiseShield",0);
				A_FaceTarget();
				A_SpawnProjectile("SoulAttack", 80, random(-4, 4), random(-45, 45), 2, random(-20, 20));
				if (random(1,10) <= 7) { A_SpawnProjectile("SoulAttack", 56, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
				if (random(1,10) <= 3) { A_SpawnProjectile("SoulAttack", 24, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
				if (random(1,20) <= 1) { A_SpawnProjectile("SoulAttack", 8, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
			}
			PENY E 1 
			{
				A_SetInventory("PennywiseShield",0);
				A_FaceTarget();
				A_SpawnProjectile("SoulAttack", 32, random(-4, 4), random(-45, 45), 2, random(-20, 20));
				if (random(1,10) <= 7) { A_SpawnProjectile("SoulAttack", 22, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
				if (random(1,10) <= 3) { A_SpawnProjectile("SoulAttack", 10, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
				if (random(1,20) <= 1) { A_SpawnProjectile("SoulAttack", 3, random(-4, 4), random(-45, 45), 2, random(-20, 20)); }
			}
			Goto See2;
		Missile:
			PENY A 0 A_ClearShadow();
			PENY E 0 A_SetInventory("PennywiseShield",0);
			PENY A 0 A_Jump(32,"Missile2");
			PENY E 9
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 240) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(8); }
				A_FaceTarget();
			}
			PENY E 4 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(3); }

				A_SpawnProjectile("Deadlight", 96, 0, 0, 1);
			}
			PENY E 9
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 240) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(8); }
				A_FaceTarget();
			}
			Goto See2;  
		Missile2:
			PENY E 9
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 240) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(8); }
				A_FaceTarget();
			}
			PENY E 4 
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(2); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 90) { A_SetTics(3); }

				A_SpawnProjectile("Deadlight", 96, -9, 0, 1);
				A_SpawnProjectile("Deadlight", 96, 9, 0, 1);
			}
			PENY E 9
			{
				if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 240) { A_SetTics(5); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 180) { A_SetTics(6); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 120) { A_SetTics(7); }
				else if (exex_monsterlevelenabledflags && CountInv("MonsterLevel") > 60) { A_SetTics(8); }
				A_FaceTarget();
			}
			Goto See2;
		Pain:
			PENY F 0
			{
				A_SetInventory("PennywiseShield",1);
				A_SetInventory("PennywiseNotShield",0);
			}
			PENY F 8 A_EEPain(1,random(4,6),32);
			PENY F 0 
			{
				if (random(1,4) == 1) { return resolvestate("See2"); }
				return resolvestate(null);
			}
			Goto PainRetaliate;
		Pain.Deadlight:
			PENY F 0 
			{
				if (random(1,16) == 1) { return resolvestate("See2"); }
				A_QuakeEx(random(1,2),random(1,2),random(1,3),random(40,70),(randompick(0,0,0,0,0,1,1,1,2)*16),1024,"PENHURT",QF_SCALEDOWN);
				A_StartSound("PENHURT",9,CHANF_DEFAULT,1.0,ATTN_NORM,0.67);
				A_StartSound("PENHURT",10,CHANF_DEFAULT,1.0,ATTN_NORM,1.5);
				A_StartSound("PENHURT",11,CHANF_DEFAULT,1.0,ATTN_NORM,0.5);
				A_StartSound("PENHURT",12,CHANF_DEFAULT,1.0,ATTN_NORM,2);
				A_StartSound("PENHURT",13,CHANF_DEFAULT,1.0,ATTN_NORM,0.8);
				A_StartSound("PENHURT",14,CHANF_DEFAULT,1.0,ATTN_NORM,1.25);
				A_SetInventory("PennywiseShield",0);
				A_SetInventory("PennywiseNotShield",1);
				bNOPAIN = true;
				return resolvestate(null);
			}
			PENY F 8 A_EEPain(1,random(18,22),8);
			PENY FFFFFFFF 8
			{
				A_SetTics(randompick(7,8,8,8,8,9));
				if (CountInv("PWDefenseBuff")) A_SetTics(randompick(5,6,6,6,6,7));
			}
			PENY F 0 A_Jump(16,17);
			PENY FFFFFFFF 8
			{
				A_SetTics(randompick(7,8,8,8,8,9));
				if (CountInv("PWDefenseBuff")) A_SetTics(randompick(5,6,6,6,6,7));
			}
			PENY F 0 A_Jump(64,8);
			PENY FFFFFFFF 8
			{
				A_SetTics(randompick(7,8,8,8,8,9));
				if (CountInv("PWDefenseBuff")) A_SetTics(randompick(5,6,6,6,6,7));
			}
			PENY FFFF 0 
			{
				A_SetInventory("PennywiseShield",1);
				A_SetInventory("PennywiseNotShield",0);
				bNOPAIN = false;
			}
			goto See2;
		PainRetaliate:
			PENY FFFF 5 
			{
				A_SetTics(randompick(4,5,5,5,5,6));
				A_SpawnProjectile("SkullSeeker666", 96,0,random(-180, 180),1,random(-20, 20));
			}
			PENY F 0 A_Jump(64,4);
			PENY FFFF 5 
			{
				A_SetTics(randompick(4,5,5,5,5,6));
				A_SpawnProjectile("SkullSeeker666", 96,0,random(-180, 180),1,random(-20, 20));
			}
			PENY FFFF 0 
			{
				A_SetInventory("PennywiseShield",1);
				A_SetInventory("PennywiseNotShield",0);
				bNOPAIN = false;
			}
			Goto See2;
		Death:
			PENY G 8
			{
				A_QuakeEx(random(3,4),random(3,4),random(4,6),random(220,340),(randompick(1,1,1,1,1,2,2,2,2)*16),4096);
			}
			PENY GGGG 8;
			PENY H 8
			{
				A_StopSound(CHAN_VOICE);
				A_StopSound(CHAN_5);
				A_StopSound(CHAN_6);
				A_StopSound(CHAN_7);
				A_StopSound(8);
				A_StartSound("pwise/death",CHAN_VOICE,CHANF_DEFAULT,1.0,ATTN_NONE,1.0);
				A_StartSound("pwise/death",CHAN_5,CHANF_DEFAULT,1.0,ATTN_NONE,0.8);
				A_StartSound("pwise/death",CHAN_6,CHANF_DEFAULT,1.0,ATTN_NONE,1.2);
				A_StartSound("pwise/death",CHAN_7,CHANF_DEFAULT,1.0,ATTN_NONE,1.1);
				A_StartSound("pwise/death",8,CHANF_DEFAULT,1.0,ATTN_NONE,0.9);
			}
			PENY IJ 8;
			PENY K 8 A_Fall();
			PENY L 1 A_SpawnProjectile("cloud1", random(24, 40), 0, 0, 0, 0);
			PENY L 1 A_SpawnProjectile("cloud1", random(24, 40), 0, 0, 0, 0);
			PENY L 0 A_SpawnProjectile("Sparkles", 8, random(-16, 16), random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY LLLL 0 A_SpawnProjectile("cloud1", random(24, 40), random(-4, 4), 0, 0, 0);
			PENY L 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY LLL 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("cloud1", random(24, 40), random(-16, 16), 0, 0, 0);
			PENY L 0 A_SpawnProjectile("cloud1", random(24, 40), random(-16, 16), 0, 0, 0);
			PENY LLLL 0 A_SpawnProjectile("cloud1", random(24, 40), random(-8, 8), 0, 0, 0);
			PENY L 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("cloud1", random(24, 40), random(-16, 16), 0, 0, 0);
			PENY L 0 A_SpawnProjectile("cloud1", random(24, 40), random(-16, 16), 0, 0, 0);
			PENY LLL 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY L 1 A_SpawnProjectile("cloud1", random(24, 40), random(-4, 4), 0, 0, 0);
			PENY LLL 1 A_SpawnProjectile("cloud1", random(24, 40), random(-2, 2), 0, 0, 0);
			PENY MM 1 A_SpawnProjectile("cloud1", random(16, 32), random(-2, 2), 0, 0, 0);
			PENY MM 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY MM 1 A_SpawnProjectile("cloud1", random(16, 32), 0, 0, 0, 0);
			PENY MM 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY MMM 0 A_SpawnProjectile("cloud1", random(16, 32), random(-4, 4), 0, 0, 0);
			PENY MM 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY MM 0 A_SpawnProjectile("cloud1", random(16, 32), 0, 0, 0, 0);
			PENY MMM 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY MM 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY MM 1 A_SpawnProjectile("cloud1", random(16, 32), random(-16, 16), 0, 0, 0);
			PENY MM 0 A_SpawnProjectile("cloud1", random(16, 32), random(-4, 4), 0, 0, 0);
			PENY MM 1 A_SpawnProjectile("cloud1", random(16, 32), random(-16, 16), 0, 0, 0);
			PENY N 1 A_SpawnProjectile("cloud1", random(14, 30), random(-2, 2), 0, 0, 0);
			PENY NNN 1 A_SpawnProjectile("cloud1", random(14, 30), random(-32, 32), 0, 0, 0);
			PENY NNNN 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY N 1 A_SpawnProjectile("cloud1", random(14, 30), random(-16, 16), 0, 0, 0);
			PENY NN 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY NN 1 A_SpawnProjectile("cloud1", random(14, 30), random(-16, 16), 0, 0, 0);
			PENY NNN 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY NN 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY N 1 A_SpawnProjectile("cloud1", random(14, 30), random(-16, 16), 0, 0, 0);
			PENY NN 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY N 1 A_SpawnProjectile("cloud1", random(14, 30), random(-16, 16), 0, 0, 0);
			PENY O 1 A_SpawnProjectile("cloud1", random(12, 24), random(-16, 16), 0, 0, 0);
			PENY OOO 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY OOO 1 A_SpawnProjectile("cloud1", random(12, 24), random(-16, 16), 0, 0, 0);
			PENY OOOO 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY OOO 1  A_SpawnProjectile("cloud1", random(12, 24), random(-16, 16), 0, 0, 0);
			PENY OOOO 1 A_SpawnProjectile("cloud1", random(12, 24), random(-16, 16), 0, 0, 0);
			PENY OO 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY OOOO 1 A_SpawnProjectile("cloud1", random(12, 24), random(-16, 16), 0, 0, 0);
			PENY PPPP 1 A_SpawnProjectile("cloud1", random(12, 20), random(-16, 16), 0, 0, 0);
			PENY PPPP 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY PPPPP 1 A_SpawnProjectile("cloud1", random(12, 20), random(-16, 16), 0, 0, 0);
			PENY PPPP 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY PPPPP 1 A_SpawnProjectile("cloud1", random(12, 20), random(-16, 16), 0, 0, 0);
			PENY PPPPP 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY PPPP 1 A_SpawnProjectile("cloud1", random(12, 20), random(-16, 16), 0, 0, 0);
			PENY PPPPP 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY PPPP 1 A_SpawnProjectile("cloud1", random(12, 20), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 1 A_SpawnProjectile("cloud1", random(10, 18), random(-16, 16), 0, 0, 0);
			PENY QQQQQQ 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 1 A_SpawnProjectile("cloud1", random(10, 16), random(-16, 16), 0, 0, 0);
			PENY RRRRRRR 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY SSSSSSSS 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY SSSSSSSS 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY SSSSSSSS 1 A_SpawnProjectile("cloud1", random(8, 14), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 1 A_SpawnProjectile("cloud1", random(8, 12), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 1 A_SpawnProjectile("cloud1", random(8, 12), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY TTTTTTTTT 1 A_SpawnProjectile("cloud1", random(8, 12), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 1 A_SpawnProjectile("cloud1", random(8, 12), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 1 A_SpawnProjectile("cloud1", random(8, 12), random(-16, 16), 0, 0, 0);
			PENY TTTTTTTTT 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY UUUUUUUUUU 1 A_SpawnProjectile("cloud1", random(6, 10), random(-16, 16), 0, 0, 0);
			PENY UUUUUUUUUU 1 A_SpawnProjectile("cloud1", random(6, 10), random(-16, 16), 0, 0, 0);
			PENY UUUUUUUUUU 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY UUUUUUUUUU 1 A_SpawnProjectile("cloud1", random(6, 10), random(-16, 16), 0, 0, 0);
			PENY UUUUUUUUUU 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY UUUUUUUUUU 1 A_SpawnProjectile("cloud1", random(6, 10), random(-16, 16), 0, 0, 0);
			PENY UUUUUUUUUU 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY VVVVVVVVVVVV 1 A_SpawnProjectile("cloud1", random(6, 8),random(-16, 16), 0, 0, 0);
			PENY VVVVVVVVVVVV 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY VVVVVVVVVVVV 1 A_SpawnProjectile("cloud1", random(6, 8), random(-16, 16), 0, 0, 0);
			PENY VVVVVVVVVVVV 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY VVVVVVVVVVVV 1 A_SpawnProjectile("cloud1", random(6, 8),random(-16, 16), 0, 0, 0);
			PENY VVVVVVVVVVVV 0 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY WWWWWWWWWWWWWW 1 A_SpawnProjectile("cloud1", random(4, 8), random(-16, 16), 0, 0, 0);
			PENY WWWWWWWWWWWWWW 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY WWWWWWWWWWWWWW 1 A_SpawnProjectile("cloud1", random(4, 8), random(-16, 16), 0, 0, 0);
			PENY WWWWWWWWWWWWWW 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY WWWWWWWWWWWWWW 1 A_SpawnProjectile("cloud1", random(4, 8), random(-16, 16), 0, 0, 0);
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("cloud1", random(2, 8), random(-16, 16), 0, 0, 0);
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("cloud1", random(2, 8), random(-16, 16), 0, 0, 0);
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("cloud1", random(2, 8), random(-16, 16), 0, 0, 0);
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("Sparkles", 8, 0, random(-180, 180), 2, random(-180, 180));
			PENY XXXXXXXXXXXXXXXX 1 A_SpawnProjectile("cloud1", random(2, 8), random(-16, 16), 0, 0, 0);
			PENY YYYYYYYYYYYYYYYYYYYY 5 A_SpawnProjectile("cloud1", random(0, 8), random(-16, 16), 0, 0, 0);
			PENY Z -1;
			Stop;
		Ice:
			goto Death;
	}
}

